# cmake/arm_arch.cmake - ggml-cpu's -march on aarch64 (docs/DGX_SPARK.md), for the engine and the vision encoder.
#
# GCC 13 does not know the GB10's Cortex-X925 / A725 cores: its -mcpu=native is plain ARMv8 (no dotprod, i8mm or SVE),
# which ggml's native path keeps.  Both builds are compiled on the PC they run on, so -march is built from what this
# CPU reports instead.  -DSTRATA_ARM_ARCH=<march> overrides it; -DSTRATA_ARM_ARCH=native keeps ggml's own detection.
function(strata_arm_ggml_arch)
  if(NOT DEFINED STRATA_ARM_ARCH)
    set(_arm_arch "armv8.2-a")
    if(EXISTS /proc/cpuinfo)
      file(STRINGS /proc/cpuinfo _arm_features REGEX "^Features" LIMIT_COUNT 1)
      string(REGEX REPLACE "^Features[ \t]*:[ \t]*" "" _arm_features "${_arm_features}")
      separate_arguments(_arm_features)
      foreach(_p "asimddp;dotprod" "asimdhp;fp16" "i8mm;i8mm" "bf16;bf16" "sve;sve" "sve2;sve2")
        list(GET _p 0 _flag)
        list(GET _p 1 _ext)
        if(_flag IN_LIST _arm_features)
          string(APPEND _arm_arch "+${_ext}")
        endif()
      endforeach()
    endif()
    set(STRATA_ARM_ARCH "${_arm_arch}" CACHE STRING "aarch64 -march for ggml-cpu (native: ggml's -mcpu=native)")
  endif()
  if(STRATA_ARM_ARCH STREQUAL "native")
    message(STATUS "Strata aarch64: ggml-cpu -mcpu=native (ggml's own detection)")
    set(GGML_NATIVE ON CACHE BOOL "" FORCE)
  else()
    message(STATUS "Strata aarch64: ggml-cpu -march=${STRATA_ARM_ARCH}")
    set(GGML_NATIVE OFF CACHE BOOL "" FORCE)
    set(GGML_CPU_ARM_ARCH "${STRATA_ARM_ARCH}" CACHE STRING "" FORCE)
  endif()
endfunction()
